import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import { Inter } from "next/font/google";
import BootstrapClient from '@/components/BootstrapClient.js';
import ChatBot from '@/components/ui/chatbot/popup/ChatBotPopup.js';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <BootstrapClient />
        <ChatBot />
      </body>
    </html>
  );
}