import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import { Inter } from "next/font/google";
import BootstrapClient from '@/components/BootstrapClient.js';
import ChatBot from '@/components/ui/chatbot/popup/ChatBotPopup.js';

/**
 * Inter font configuration.
 */
const inter = Inter({ subsets: ['latin'] });

/**
 * Metadata for the application.
 * @type {{title: string, description: string}}
 */
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

/**
 * Root layout component.
 * @param {Object} props - The properties object.
 * @param {React.ReactNode} props.children - The child components to be rendered.
 * @returns {JSX.Element} The root layout component.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <BootstrapClient />
        <ChatBot />
      </body>
    </html>
  );
}